"""Managing a delimited block inside a file BEARING does not own.

@see ADR-0003 — AGENTS.md is the repository's document; BEARING owns a region.
Accepted Contracts compile into that region.

`AGENTS.md` and `CLAUDE.md` are the repository's own documents. They accumulate
team conventions, onboarding notes, and local quirks that have nothing to do with
BEARING, and overwriting them is the fastest available way to get BEARING
removed from a repository.

So BEARING owns a region, not a file:

    <!-- BEARING:START v1 ... -->
    ...managed content...
    <!-- BEARING:END -->

Everything outside the markers is never read, moved, or rewritten. The block is
replaced in place on every render, which makes the operation idempotent: running
`bearing render` twice produces the same file, and a hand-edit inside the block
is reported as drift rather than silently preserved or silently lost.

`AGENTS.md` is at the repository *root* for a discovery reason. Codex walks from
the project root down to the working directory checking `AGENTS.md` in each
directory, so a constitution parked at `.agents/AGENTS.md` is never loaded by
Codex at all -- it would only apply to sessions whose working directory was
inside `.agents/`. Cursor happens to pick that path up, which is exactly what
makes the mistake easy to miss.
"""

from __future__ import annotations

import os
import re
from typing import List, Optional, Tuple

from . import __version__
from .config import ResolvedConfig
from .paths import template_path
from .util import read_text, write_text

MARKER_VERSION = "v1"
START = "<!-- BEARING:START %s — generated by `bearing render`; edit the canonical source, not this block -->" % MARKER_VERSION
END = "<!-- BEARING:END -->"

_BLOCK_RE = re.compile(
    r"<!--\s*BEARING:START.*?-->.*?<!--\s*BEARING:END\s*-->",
    re.DOTALL,
)

_DEFAULT_AGENTS_HEADER = """# AGENTS.md — Repository Constitution

Instructions for any agent working in this repository.
"""

_CLAUDE_POINTER = """This repository's agent instructions live in [`AGENTS.md`](AGENTS.md). Read that file; it is the single source of truth.

BEARING deliberately does not duplicate the constitution here. Two copies of the same governance text drift, and a stale copy is worse than no copy because it still reads authoritative."""


def rule_body(config: ResolvedConfig) -> str:
    """The canonical rule text, with this repository's paths substituted in.

    One template, so the same wording reaches `AGENTS.md`, `.cursor/rules/`, and
    `.github/copilot-instructions.md`. Nothing hardcodes `docs/decisions`: a
    repository that has used `docs/adr/` for a decade gets a constitution that
    names `docs/adr/`.
    """
    from .decisions import contracts_digest

    template = read_text(template_path("agents-block.md")) or ""
    layout = config.layout
    replacements = {
        "decisions_path": layout.decisions_rel,
        "index_file": layout.index_name,
        "shadow_dir": layout.shadow_name,
        "transcripts_dir": layout.transcripts_name,
        "version": __version__,
        "contracts_section": contracts_digest(layout).rstrip(),
    }
    for key, value in replacements.items():
        template = template.replace("{{%s}}" % key, str(value))
    return template.strip() + "\n"


def compose_block(body: str) -> str:
    return "%s\n\n%s\n%s" % (START, body.strip(), END)


def apply_block(path: str, body: str, create_header: Optional[str] = None) -> Tuple[bool, str]:
    """Insert or replace the managed block. Returns (changed, action)."""
    block = compose_block(body)
    existing = read_text(path)

    if existing is None:
        content = "%s\n%s\n" % (create_header or _DEFAULT_AGENTS_HEADER, block)
        return write_text(path, content), "created"

    if _BLOCK_RE.search(existing):
        updated = _BLOCK_RE.sub(lambda _: block, existing, count=1)
        return write_text(path, updated), "updated"

    separator = "" if existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    updated = "%s%s%s\n" % (existing, separator, block)
    return write_text(path, updated), "appended"


def check_block(path: str, body: str) -> Optional[str]:
    """Return a drift description, or None when the block is current."""
    existing = read_text(path)
    if existing is None:
        return "%s does not exist" % path
    match = _BLOCK_RE.search(existing)
    if not match:
        return "%s has no BEARING block" % path
    if match.group(0).strip() != compose_block(body).strip():
        return "the BEARING block in %s has drifted from its canonical source" % path
    return None


def strip_block(path: str) -> bool:
    """Remove the managed block, leaving the rest of the file untouched.

    Used by `bearing uninstall`. Removing BEARING must not take the
    repository's own agent instructions with it -- a framework you cannot cleanly
    back out of is a framework nobody is willing to try.
    """
    existing = read_text(path)
    if existing is None or not _BLOCK_RE.search(existing):
        return False
    updated = _BLOCK_RE.sub("", existing, count=1)
    updated = re.sub(r"\n{3,}", "\n\n", updated).rstrip("\n") + "\n"
    return write_text(path, updated)


def targets(config: ResolvedConfig) -> List[Tuple[str, str, Optional[str]]]:
    """Files whose blocks BEARING manages: (path, body, header-if-creating).

    `AGENTS.md` is created when absent, because every repository needs a
    constitution and BEARING is entitled to establish one.

    `CLAUDE.md` is only touched when it already exists, and then only with a
    pointer. Creating it would add a second governance file to a repository that
    had one, and filling it with the constitution would create the duplicate this
    architecture forbids everywhere else.
    """
    rules = config.get("projections.rules") or {}
    configured = list(rules.get("targets") or [])
    out: List[Tuple[str, str, Optional[str]]] = []

    if "agents-md" in configured:
        out.append((os.path.join(config.workspace, "AGENTS.md"), rule_body(config), None))

    claude_path = os.path.join(config.workspace, "CLAUDE.md")
    if "claude" in configured and os.path.isfile(claude_path):
        out.append((claude_path, _CLAUDE_POINTER, None))

    return out
